In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df=pd.read_csv("data/data_gempa_preprocessed.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157332 entries, 0 to 157331
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   157332 non-null  object
 1   province_id          157332 non-null  object
 2   place                157332 non-null  object
 3   time                 157332 non-null  object
 4   date                 157332 non-null  object
 5   month                157332 non-null  int64
 6   month_name           157332 non-null  object
 7   year                 157332 non-null  int64
 8   latitude             157332 non-null  float64
 9   longitude            157332 non-null  float64
 10  magnitude            157332 non-null  float64
 11  depth                157332 non-null  float64
 12  depth_category       157332 non-null  object
 13  fault_megathrust_id  12916 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 16.8+ MB

In [4]:

df["time"] = pd.to_datetime(df["time"], errors="coerce")
df = df.dropna(subset=["time"])
df["time"].dtype

dtype('<M8[ns]')

In [5]:
def create_event_text(row):
    date_str = row["time"].strftime("%d %B %Y")
    time_str = row["time"].strftime("%H:%M")
    
    text = (
        f"Pada tanggal {date_str} pukul {time_str} WIB terjadi gempa bumi "
        f"di Provinsi {row['place']} dengan magnitudo {row['magnitude']} "
        f"dan kedalaman {row['depth']} km. "
        f"Gempa ini termasuk gempa {row['depth_category']} "
        f"dan berlokasi pada koordinat lintang {row['latitude']} "
        f"dan bujur {row['longitude']}."
    )
    
    return text

In [ ]:
df["event_text"] = df.apply(create_event_text, axis=1)
df[["event_text"]].head(10)

                                                                                                                                                                                                                                        event_text
0             Pada tanggal 01 January 2024 pukul 13:46 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.6246 dan bujur 107.7514.
1  Pada tanggal 01 January 2024 pukul 07:52 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.3 dan kedalaman 81.212 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.1092 dan bujur 123.6177.
2       Pada tanggal 01 January 2024 pukul 05:22 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
3          Pada tanggal 31 December 2023 pukul 13:34 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.8 dan kedalaman 12.158 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.7592 dan bujur 107.8299.
4                  Pada tanggal 30 December 2023 pukul 17:16 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.

In [8]:
df[["event_text"]].head(10)

                                                                                                                                                                                                                                         event_text
0              Pada tanggal 01 January 2024 pukul 13:46 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.6246 dan bujur 107.7514.
1   Pada tanggal 01 January 2024 pukul 07:52 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.3 dan kedalaman 81.212 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.1092 dan bujur 123.6177.
2        Pada tanggal 01 January 2024 pukul 05:22 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
3           Pada tanggal 31 December 2023 pukul 13:34 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.8 dan kedalaman 12.158 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.7592 dan bujur 107.8299.
4                   Pada tanggal 30 December 2023 pukul 17:16 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.
5         Pada tanggal 29 December 2023 pukul 19:18 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.
6           Pada tanggal 28 December 2023 pukul 22:48 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.6 dan kedalaman 47.743 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 1.156 dan bujur 126.3562.
7      Pada tanggal 27 December 2023 pukul 22:43 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 5.1 dan kedalaman 72.197 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -7.7769 dan bujur 107.9533.
8  Pada tanggal 27 December 2023 pukul 18:52 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 5.0 dan kedalaman 39.974 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -9.9486 dan bujur 123.7035.
9     Pada tanggal 26 December 2023 pukul 11:12 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.

In [9]:
df["metadata"] = df.apply(
    lambda row: {
        "province": row["place"],
        "date": str(row["date"]),
        "year": int(row["year"]),
        "month": int(row["month"]),
        "depth_category": row["depth_category"],
        "magnitude": row["magnitude"]
    },
    axis=1
)

In [11]:
documents = [
    {
        "text": row["event_text"],
        "metadata": row["metadata"]
    }
    for _, row in df.iterrows()
]

In [12]:
documents

[{'text': 'Pada tanggal 01 January 2024 pukul 13:46 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.6246 dan bujur 107.7514.',
  'metadata': {'province': 'Jawa Barat',
   'date': '2024-01-01',
   'year': 2024,
   'month': 1,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 01 January 2024 pukul 07:52 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.3 dan kedalaman 81.212 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.1092 dan bujur 123.6177.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '2024-01-01',
   'year': 2024,
   'month': 1,
   'depth_category': 'intermediate',
   'magnitude': 5.3}},
 {'text': 'Pada tanggal 01 January 2024 pukul 05:22 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '2024-01-01',
   'year': 2024,
   'month': 1,
   'depth_category': 'shallow',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 31 December 2023 pukul 13:34 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.8 dan kedalaman 12.158 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.7592 dan bujur 107.8299.',
  'metadata': {'province': 'Jawa Barat',
   'date': '2023-12-31',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 30 December 2023 pukul 17:16 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.',
  'metadata': {'province': 'Papua',
   'date': '2023-12-30',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 6.3}},
 {'text': 'Pada tanggal 29 December 2023 pukul 19:18 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-29',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 28 December 2023 pukul 22:48 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.6 dan kedalaman 47.743 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 1.156 dan bujur 126.3562.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-28',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 27 December 2023 pukul 22:43 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 5.1 dan kedalaman 72.197 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -7.7769 dan bujur 107.9533.',
  'metadata': {'province': 'Jawa Barat',
   'date': '2023-12-27',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 5.1}},
 {'text': 'Pada tanggal 27 December 2023 pukul 18:52 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 5.0 dan kedalaman 39.974 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -9.9486 dan bujur 123.7035.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '2023-12-27',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 26 December 2023 pukul 11:12 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '2023-12-26',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 26 December 2023 pukul 08:59 WIB terjadi gempa bumi di Provinsi Sulawesi Tengah dengan magnitudo 4.5 dan kedalaman 133.502 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.0357 dan bujur 122.9301.',
  'metadata': {'province': 'Sulawesi Tengah',
   'date': '2023-12-26',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 26 December 2023 pukul 06:42 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.7 dan kedalaman 47.429 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 4.0237 dan bujur 126.6495.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '2023-12-26',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 26 December 2023 pukul 03:31 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Barat dengan magnitudo 4.6 dan kedalaman 141.603 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -8.583 dan bujur 118.2004.',
  'metadata': {'province': 'Nusa Tenggara Barat',
   'date': '2023-12-26',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 25 December 2023 pukul 06:30 WIB terjadi gempa bumi di Provinsi Gorontalo dengan magnitudo 4.6 dan kedalaman 230.316 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang 0.3607 dan bujur 123.1898.',
  'metadata': {'province': 'Gorontalo',
   'date': '2023-12-25',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 24 December 2023 pukul 20:31 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 109.751 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang 5.0747 dan bujur 126.0217.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '2023-12-24',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 24 December 2023 pukul 06:00 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '2023-12-24',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2023 pukul 15:07 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-23',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2023 pukul 09:09 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '2023-12-23',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2023 pukul 03:48 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.357 dan bujur 129.6802.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-23',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 22 December 2023 pukul 11:33 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 5.1 dan kedalaman 62.909 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang 2.6388 dan bujur 128.1978.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-22',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 5.1}},
 {'text': 'Pada tanggal 20 December 2023 pukul 20:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.6 dan kedalaman 54.434 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -0.6899 dan bujur 127.0738.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-20',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 20 December 2023 pukul 15:59 WIB terjadi gempa bumi di Provinsi Sulawesi Tengah dengan magnitudo 4.5 dan kedalaman 141.084 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.0928 dan bujur 123.0929.',
  'metadata': {'province': 'Sulawesi Tengah',
   'date': '2023-12-20',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 19 December 2023 pukul 23:35 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.5 dan kedalaman 50.145 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 3.2291 dan bujur 126.9565.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '2023-12-19',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 19 December 2023 pukul 22:36 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 5.2 dan kedalaman 173.775 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang 2.7011 dan bujur 128.2749.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-19',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 19 December 2023 pukul 12:48 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -0.9024 dan bujur 126.79.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-19',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 19 December 2023 pukul 02:43 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.9 dan kedalaman 591.214 km. Gempa ini termasuk gempa deep dan berlokasi pada koordinat lintang -7.2501 dan bujur 119.1459.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '2023-12-19',
   'year': 2023,
   'month': 12,
   'depth_category': 'deep',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 18 December 2023 pukul 22:20 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.',
  'metadata': {'province': 'Aceh',
   'date': '2023-12-18',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 18 December 2023 pukul 10:18 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '2023-12-18',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 18 December 2023 pukul 09:17 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-18',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 17 December 2023 pukul 16:40 WIB terjadi gempa bumi di Provinsi Papua Pegunungan dengan magnitudo 4.6 dan kedalaman 42.306 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -3.3023 dan bujur 138.4537.',
  'metadata': {'province': 'Papua Pegunungan',
   'date': '2023-12-17',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 17 December 2023 pukul 14:27 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 5.1 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -2.4708 dan bujur 140.1438.',
  'metadata': {'province': 'Papua',
   'date': '2023-12-17',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 5.1}},
 {'text': 'Pada tanggal 17 December 2023 pukul 00:47 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -3.2127 dan bujur 130.56.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-17',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 16 December 2023 pukul 06:45 WIB terjadi gempa bumi di Provinsi Sumatera Barat dengan magnitudo 5.0 dan kedalaman 51.179 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -0.3273 dan bujur 98.8494.',
  'metadata': {'province': 'Sumatera Barat',
   'date': '2023-12-16',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 16 December 2023 pukul 03:29 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.5 dan kedalaman 33.83 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 1.0036 dan bujur 125.9371.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-16',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 15 December 2023 pukul 04:41 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.5 dan kedalaman 48.662 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 1.6227 dan bujur 126.6154.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-15',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 15 December 2023 pukul 00:02 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.9 dan kedalaman 158.377 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -6.8918 dan bujur 129.5256.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-15',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 14 December 2023 pukul 17:49 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 116.052 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -6.7879 dan bujur 130.4237.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-14',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 14 December 2023 pukul 07:27 WIB terjadi gempa bumi di Provinsi Banten dengan magnitudo 4.8 dan kedalaman 40.422 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.2237 dan bujur 105.9547.',
  'metadata': {'province': 'Banten',
   'date': '2023-12-14',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 14 December 2023 pukul 01:05 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.0 dan kedalaman 104.287 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang 0.1199 dan bujur 124.0114.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '2023-12-14',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 13 December 2023 pukul 23:35 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.5 dan kedalaman 10.4 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.8597 dan bujur 106.5246.',
  'metadata': {'province': 'Jawa Barat',
   'date': '2023-12-13',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 13 December 2023 pukul 14:30 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.8 dan kedalaman 161.226 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -7.3417 dan bujur 128.669.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-13',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 13 December 2023 pukul 11:08 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 29.597 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 2.0407 dan bujur 96.7775.',
  'metadata': {'province': 'Aceh',
   'date': '2023-12-13',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 11 December 2023 pukul 18:51 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.5 dan kedalaman 50.457 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang 2.4633 dan bujur 126.7122.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-11',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 11 December 2023 pukul 10:16 WIB terjadi gempa bumi di Provinsi Riau dengan magnitudo 5.0 dan kedalaman 255.387 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.4441 dan bujur 101.3587.',
  'metadata': {'province': 'Riau',
   'date': '2023-12-11',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 11 December 2023 pukul 04:33 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.8 dan kedalaman 122.003 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang 2.6627 dan bujur 128.2722.',
  'metadata': {'province': 'Maluku Utara',
   'date': '2023-12-11',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 11 December 2023 pukul 03:50 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.0 dan kedalaman 57.124 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.9464 dan bujur 127.5926.',
  'metadata': {'province': 'Maluku',
   'date': '2023-12-11',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 10 December 2023 pukul 19:52 WIB terjadi gempa bumi di Provinsi Papua Pegunungan dengan magnitudo 5.0 dan kedalaman 10.356 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -4.4103 dan bujur 139.4579.',
  'metadata': {'province': 'Papua Pegunungan',
   'date': '2023-12-10',
   'year': 2023,
   'month': 12,
   'depth_category': 'shallow',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 10 December 2023 pukul 04:49 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 5.1 dan kedalaman 61.048 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -3.6376 dan bujur 140.6335.',
  'metadata': {'province': 'Papua',
   'date': '2023-12-10',
   'year': 2023,
   'month': 12,
   'depth_category': 'intermediate',
   'magnitude': 5.1}},
 {'text': 'Pada tanggal 09 December 2023 pukul 23:27 WIB terjadi gempa bumi di Provinsi Sulawesi Tengah dengan magnitudo 4.6 dan kedalaman 576.502 km. Gempa ini termasuk gempa deep dan berlokasi pada koordinat lintang 1.0045 dan bujur 120.7906.',
  'metadata': {'province': 'Sulawesi Tengah',
   'date': '2023-12-09',
   'year': 2023,
   'month': 12,
   'depth_category': 'deep',
   'magnitude': 4.6}},