In [19]:
import pandas as pd
import numpy as np
from langchain_openai import OpenAIEmbeddings
import os
from langchain_community.vectorstores import Chroma

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [6]:
df=pd.read_csv("data/data_gempa_preprocessed.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157332 entries, 0 to 157331
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   157332 non-null  object
 1   province_id          157332 non-null  object
 2   place                157332 non-null  object
 3   time                 157332 non-null  object
 4   date                 157332 non-null  object
 5   month                157332 non-null  int64
 6   month_name           157332 non-null  object
 7   year                 157332 non-null  int64
 8   latitude             157332 non-null  float64
 9   longitude            157332 non-null  float64
 10  magnitude            157332 non-null  float64
 11  depth                157332 non-null  float64
 12  depth_category       157332 non-null  object
 13  fault_megathrust_id  12916 non-null   object
 14  Unnamed: 14          0 non-null       float64
dtypes: float64(5), int64(2), object(8)
memory usage: 18.0+ MB

In [7]:

df["time"] = pd.to_datetime(df["time"], errors="coerce")
df = df.dropna(subset=["time"])
df["time"].dtype

C:\Users\calys\AppData\Local\Temp\ipykernel_21588\1419726095.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["time"] = pd.to_datetime(df["time"], errors="coerce")

dtype('<M8[ns]')

In [8]:
def create_event_text(row):
    date_str = row["time"].strftime("%d %B %Y")
    time_str = row["time"].strftime("%H:%M")
    
    text = (
        f"Pada tanggal {date_str} pukul {time_str} WIB terjadi gempa bumi "
        f"di Provinsi {row['place']} dengan magnitudo {row['magnitude']} "
        f"dan kedalaman {row['depth']} km. "
        f"Gempa ini termasuk gempa {row['depth_category']} "
        f"dan berlokasi pada koordinat lintang {row['latitude']} "
        f"dan bujur {row['longitude']}."
    )
    
    return text

In [9]:
df["event_text"] = df.apply(create_event_text, axis=1)
df[["event_text"]].head(10)

                                                                                                                                                                                                                                          event_text
2        Pada tanggal 23 December 2025 pukul 22:53 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
4                    Pada tanggal 23 December 2025 pukul 16:23 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.
5              Pada tanggal 23 December 2025 pukul 18:20 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.
9      Pada tanggal 23 December 2025 pukul 12:50 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.
15     Pada tanggal 23 December 2025 pukul 00:52 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.
16            Pada tanggal 23 December 2025 pukul 07:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.
17        Pada tanggal 23 December 2025 pukul 09:16 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.
26                    Pada tanggal 23 December 2025 pukul 20:45 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.
27  Pada tanggal 23 December 2025 pukul 18:55 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.
28               Pada tanggal 23 December 2025 pukul 17:41 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.

In [10]:
df[["event_text"]].head(10)

                                                                                                                                                                                                                                          event_text
2        Pada tanggal 23 December 2025 pukul 22:53 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
4                    Pada tanggal 23 December 2025 pukul 16:23 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.
5              Pada tanggal 23 December 2025 pukul 18:20 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.
9      Pada tanggal 23 December 2025 pukul 12:50 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.
15     Pada tanggal 23 December 2025 pukul 00:52 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.
16            Pada tanggal 23 December 2025 pukul 07:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.
17        Pada tanggal 23 December 2025 pukul 09:16 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.
26                    Pada tanggal 23 December 2025 pukul 20:45 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.
27  Pada tanggal 23 December 2025 pukul 18:55 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.
28               Pada tanggal 23 December 2025 pukul 17:41 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.

In [11]:
df["metadata"] = df.apply(
    lambda row: {
        "province": row["place"],
        "date": str(row["date"]),
        "year": int(row["year"]),
        "month": int(row["month"]),
        "depth_category": row["depth_category"],
        "magnitude": row["magnitude"]
    },
    axis=1
)

In [12]:
documents = [
    {
        "text": row["event_text"],
        "metadata": row["metadata"]
    }
    for _, row in df.iterrows()
]

In [13]:
documents

[{'text': 'Pada tanggal 23 December 2025 pukul 22:53 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '1/1/2024',
   'year': 2024,
   'month': 1,
   'depth_category': 'dangkal',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 23 December 2025 pukul 16:23 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.',
  'metadata': {'province': 'Papua',
   'date': '12/30/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 6.3}},
 {'text': 'Pada tanggal 23 December 2025 pukul 18:20 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.',
  'metadata': {'province': 'Maluku',
   'date': '12/29/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 12:50 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '12/26/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 00:52 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '12/24/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 07:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.',
  'metadata': {'province': 'Maluku Utara',
   'date': '12/23/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 09:16 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/23/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 20:45 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.',
  'metadata': {'province': 'Aceh',
   'date': '12/18/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 18:55 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '12/18/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 23 December 2025 pukul 17:41 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.',
  'metadata': {'province': 'Maluku',
   'date': '12/18/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 02:09 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.9 dan kedalaman 158.377 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -6.8918 dan bujur 129.5256.',
  'metadata': {'province': 'Maluku',
   'date': '12/15/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 05:49 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.0 dan kedalaman 104.287 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 0.1199 dan bujur 124.0114.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/14/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 08:56 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 29.597 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 2.0407 dan bujur 96.7775.',
  'metadata': {'province': 'Aceh',
   'date': '12/13/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 16:39 WIB terjadi gempa bumi di Provinsi Riau dengan magnitudo 5.0 dan kedalaman 255.387 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -0.4441 dan bujur 101.3587.',
  'metadata': {'province': 'Riau',
   'date': '12/11/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 03:41 WIB terjadi gempa bumi di Provinsi Sumatera Barat dengan magnitudo 4.6 dan kedalaman 35.243 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.6009 dan bujur 99.9941.',
  'metadata': {'province': 'Sumatera Barat',
   'date': '12/8/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 09:20 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 5.0 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -1.1405 dan bujur 126.8473.',
  'metadata': {'province': 'Maluku Utara',
   'date': '12/7/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 01:27 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.6 dan kedalaman 41.408 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 3.1941 dan bujur 126.6826.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/6/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:33 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.8 dan kedalaman 46.238 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 3.5472 dan bujur 126.8715.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/4/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 23 December 2025 pukul 01:00 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.5 dan kedalaman 117.236 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.0345 dan bujur 129.6876.',
  'metadata': {'province': 'Maluku',
   'date': '12/2/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 5.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 08:41 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 175.981 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -8.0933 dan bujur 119.8861.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/30/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 02:12 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 4.5 dan kedalaman 34.463 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -3.4719 dan bujur 139.7516.',
  'metadata': {'province': 'Papua',
   'date': '11/29/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 19:27 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.5 dan kedalaman 229.969 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 2.6829 dan bujur 128.5208.',
  'metadata': {'province': 'Maluku Utara',
   'date': '11/28/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 06:33 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 4.6 dan kedalaman 26.899 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.3376 dan bujur 139.1478.',
  'metadata': {'province': 'Papua',
   'date': '11/26/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:47 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 148.42 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 1.3425 dan bujur 127.9982.',
  'metadata': {'province': 'Maluku Utara',
   'date': '11/26/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:50 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 7.439 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1992 dan bujur 129.8018.',
  'metadata': {'province': 'Maluku',
   'date': '11/24/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 12:14 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 5.2 dan kedalaman 17.009 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -0.5476 dan bujur 135.8426.',
  'metadata': {'province': 'Papua',
   'date': '11/21/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 04:54 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.2753 dan bujur 129.5428.',
  'metadata': {'province': 'Maluku',
   'date': '11/20/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 01:33 WIB terjadi gempa bumi di Provinsi Sumatera Barat dengan magnitudo 4.9 dan kedalaman 23.026 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9945 dan bujur 100.0625.',
  'metadata': {'province': 'Sumatera Barat',
   'date': '11/18/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 02:18 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 5.2 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.4108 dan bujur 138.8023.',
  'metadata': {'province': 'Papua',
   'date': '11/17/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:48 WIB terjadi gempa bumi di Provinsi Papua Pegunungan dengan magnitudo 5.1 dan kedalaman 93.322 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -3.785 dan bujur 138.674.',
  'metadata': {'province': 'Papua Pegunungan',
   'date': '11/16/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 5.1}},
 {'text': 'Pada tanggal 23 December 2025 pukul 23:36 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 116.744 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -8.8087 dan bujur 124.09.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/15/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:04 WIB terjadi gempa bumi di Provinsi Bengkulu dengan magnitudo 4.8 dan kedalaman 56.133 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -3.5315 dan bujur 101.4988.',
  'metadata': {'province': 'Bengkulu',
   'date': '11/15/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 23 December 2025 pukul 19:55 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3856 dan bujur 125.7397.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:47 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.6 dan kedalaman 75.656 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 4.9181 dan bujur 126.4698.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 17:24 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 9.991 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.2657 dan bujur 129.716.',
  'metadata': {'province': 'Maluku',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 22:51 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.2 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.8841 dan bujur 130.1522.',
  'metadata': {'province': 'Maluku',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 06:16 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 5.2 dan kedalaman 42.657 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.9173 dan bujur 123.699.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/12/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 07:29 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.6 dan kedalaman 35.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -10.1256 dan bujur 123.6626.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/11/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 10:53 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1155 dan bujur 130.032.',
  'metadata': {'province': 'Maluku',
   'date': '11/11/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:31 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 4.7 dan kedalaman 26.513 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -1.9507 dan bujur 139.3305.',
  'metadata': {'province': 'Papua',
   'date': '11/11/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 23 December 2025 pukul 20:12 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1476 dan bujur 130.1327.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 13:35 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.3 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.0958 dan bujur 130.1099.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.3}},
 {'text': 'Pada tanggal 23 December 2025 pukul 08:55 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1227 dan bujur 130.1012.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 05:58 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.0 dan kedalaman 8.578 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.104 dan bujur 129.9405.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 22:56 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 112.072 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.0405 dan bujur 129.6776.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 18:43 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.8 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.9168 dan bujur 129.9853.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:03 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.8638 dan bujur 130.0319.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:18 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.0168 dan bujur 130.003.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 13:18 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.6651 dan bujur 130.2065.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 12:56 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.3451 dan bujur 129.5232.',
  'metadata': {'province': 'Maluku',
   'date': '11/9/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},

In [14]:
texts = [doc["text"] for doc in documents]
metadatas = [doc["metadata"] for doc in documents]

In [17]:
os.environ["OPENAI_API_KEY"] = "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"
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

In [22]:
vectorstore = Chroma.from_texts(
    texts=texts,
    embedding=embeddings,
    metadatas=metadatas,
    persist_directory="chroma_gempa_db"
)
vectorstore.persist()

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [ ]:
vectorstore = Chroma(
    collection_name="anime_docs",
    embedding_function=embeddings,
    persist_directory="./chroma_db"
)