In [ ]:
import pandas as pd
import numpy as np

In [13]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [5]:
df=pd.read_csv("data/data_gempa_preprocessed.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157332 entries, 0 to 157331
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   157332 non-null  object
 1   province_id          157332 non-null  object
 2   place                157332 non-null  object
 3   time                 157332 non-null  object
 4   date                 157332 non-null  object
 5   month                157332 non-null  int64
 6   month_name           157332 non-null  object
 7   year                 157332 non-null  int64
 8   latitude             157332 non-null  float64
 9   longitude            157332 non-null  float64
 10  magnitude            157332 non-null  float64
 11  depth                157332 non-null  float64
 12  depth_category       157332 non-null  object
 13  fault_megathrust_id  12916 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 16.8+ MB

In [11]:

df["time"] = pd.to_datetime(df["time"], errors="coerce")
df = df.dropna(subset=["time"])
df["time"].dtype

dtype('<M8[ns]')

In [ ]:
def create_event_text(row):
    date_str = row["time"].strftime("%d %B %Y")
    time_str = row["time"].strftime("%H:%M")
    
    text = (
        f"Pada tanggal {date_str} pukul {time_str} WIB terjadi gempa bumi "
        f"di Provinsi {row['place']} dengan magnitudo {row['magnitude']} "
        f"dan kedalaman {row['depth']} km. "
        f"Gempa ini termasuk gempa {row['depth_category']} "
        f"dan berlokasi pada koordinat lintang {row['latitude']} "
        f"dan bujur {row['longitude']}."
    )
    
    return text

In [14]:
df["event_text"] = df.apply(create_event_text, axis=1)
df[["event_text"]].head()

C:\Users\calys\AppData\Local\Temp\ipykernel_8680\1346447315.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["event_text"] = df.apply(create_event_text, axis=1)

                                                                                                                                                                                                                                        event_text
0             Pada tanggal 01 January 2024 pukul 13:46 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.6246 dan bujur 107.7514.
1  Pada tanggal 01 January 2024 pukul 07:52 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.3 dan kedalaman 81.212 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.1092 dan bujur 123.6177.
2       Pada tanggal 01 January 2024 pukul 05:22 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
3          Pada tanggal 31 December 2023 pukul 13:34 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.8 dan kedalaman 12.158 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.7592 dan bujur 107.8299.
4                  Pada tanggal 30 December 2023 pukul 17:16 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.

In [15]:
df.head()

,id,province_id,place,time,date,month,month_name,year,latitude,longitude,magnitude,depth,depth_category,fault_megathrust_id,event_text
0,a4b01772-b735-4621-8a86-5c00c2367ab6,1c2639a3-f336-4c06-a4e4-a341c8be27ea,Jawa Barat,2024-01-01 13:46:45.922,2024-01-01,1,January,2024,-6.6246,107.7514,4.5,10.000,shallow,NaN,Pada tanggal 01 January 2024 pukul 13:46 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.6246 dan bujur 107.7514.
1,c7d24fdb-1f06-45a6-9fd7-03b12985c0a2,2b1b177b-b16d-439f-ad73-6020479b52e6,Sulawesi Utara,2024-01-01 07:52:43.251,2024-01-01,1,January,2024,-0.1092,123.6177,5.3,81.212,intermediate,NaN,Pada tanggal 01 January 2024 pukul 07:52 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.3 dan kedalaman 81.212 km. Gempa ini termasuk gempa intermediate dan berlokasi pada koordinat lintang -0.1092 dan bujur 123.6177.
2,3b2a4091-8bbb-4c19-9e0a-0c462fc425a9,ad662a32-5c83-4457-89ae-1b17fa08d474,Sulawesi Selatan,2024-01-01 05:22:53.884,2024-01-01,1,January,2024,-7.8936,117.8591,4.7,10.000,shallow,NaN,Pada tanggal 01 January 2024 pukul 05:22 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
3,23ab9c92-b0e5-4d25-a0f8-c2dbe73e4a08,1c2639a3-f336-4c06-a4e4-a341c8be27ea,Jawa Barat,2023-12-31 13:34:21.255,2023-12-31,12,December,2023,-6.7592,107.8299,4.8,12.158,shallow,NaN,Pada tanggal 31 December 2023 pukul 13:34 WIB terjadi gempa bumi di Provinsi Jawa Barat dengan magnitudo 4.8 dan kedalaman 12.158 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -6.7592 dan bujur 107.8299.
4,aa49a60c-1d77-4f0d-b555-021bbf0d50a7,7bbb1a43-2607-492c-a4cf-42de2b54b72f,Papua,2023-12-30 17:16:23.833,2023-12-30,12,December,2023,-2.9934,139.3720,6.3,33.000,shallow,NaN,Pada tanggal 30 December 2023 pukul 17:16 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa shallow dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.