In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("data/data_gempa_processed.csv")
df.head()

,id,province_id,place,date,month,month_name,year,latitude,longitude,magnitude,depth,depth_category,fault_megathrust_id,time
0,a4b01772-b735-4621-8a86-5c00c2367ab6,1c2639a3-f336-4c06-a4e4-a341c8be27ea,Jawa Barat,1/1/2024,1,January,2024,-6.6246,107.7514,4.5,10.000,dangkal,NaN,2024-01-01 13:46:45.922
1,c7d24fdb-1f06-45a6-9fd7-03b12985c0a2,2b1b177b-b16d-439f-ad73-6020479b52e6,Sulawesi Utara,1/1/2024,1,January,2024,-0.1092,123.6177,5.3,81.212,menengah,NaN,2024-01-01 07:52:43.251
2,3b2a4091-8bbb-4c19-9e0a-0c462fc425a9,ad662a32-5c83-4457-89ae-1b17fa08d474,Sulawesi Selatan,1/1/2024,1,January,2024,-7.8936,117.8591,4.7,10.000,dangkal,NaN,2024-01-01 05:22:53.884
3,23ab9c92-b0e5-4d25-a0f8-c2dbe73e4a08,1c2639a3-f336-4c06-a4e4-a341c8be27ea,Jawa Barat,12/31/2023,12,December,2023,-6.7592,107.8299,4.8,12.158,dangkal,NaN,2023-12-31 13:34:21.255
4,aa49a60c-1d77-4f0d-b555-021bbf0d50a7,7bbb1a43-2607-492c-a4cf-42de2b54b72f,Papua,12/30/2023,12,December,2023,-2.9934,139.3720,6.3,33.000,dangkal,NaN,2023-12-30 17:16:23.833

In [15]:
df = df.reset_index(drop=True)
df["id"] = df.index + 1

df = df.drop(columns=["province_id"])

In [18]:
df = df.rename(columns={"place": "province"})

In [16]:
print('Jumlah province_id unik:', df['id'].nunique())
print('\nContoh 10 province_id unik:')
print(df['id'].unique()[:100])

Jumlah province_id unik: 157332

Contoh 10 province_id unik:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

In [19]:
df.head()

,id,province,date,month,month_name,year,latitude,longitude,magnitude,depth,depth_category,fault_megathrust_id,time
0,1,Jawa Barat,1/1/2024,1,January,2024,-6.6246,107.7514,4.5,10.000,dangkal,NaN,2024-01-01 13:46:45.922
1,2,Sulawesi Utara,1/1/2024,1,January,2024,-0.1092,123.6177,5.3,81.212,menengah,NaN,2024-01-01 07:52:43.251
2,3,Sulawesi Selatan,1/1/2024,1,January,2024,-7.8936,117.8591,4.7,10.000,dangkal,NaN,2024-01-01 05:22:53.884
3,4,Jawa Barat,12/31/2023,12,December,2023,-6.7592,107.8299,4.8,12.158,dangkal,NaN,2023-12-31 13:34:21.255
4,5,Papua,12/30/2023,12,December,2023,-2.9934,139.3720,6.3,33.000,dangkal,NaN,2023-12-30 17:16:23.833

In [12]:
df = df[
    (df["magnitude"] > 0) &
    (df["depth"] >= 0) &
    (df["latitude"].between(-90, 90)) &
    (df["longitude"].between(-180, 180))
]

Normalisasi Waktu

In [13]:
df["time"] = pd.to_datetime(df["time"], errors="coerce")
df["date"] = df["time"].dt.date
df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["month_name"] = df["time"].dt.month_name()
df.head()

,id,province_id,time,latitude,longitude,magnitude,depth,place,fault_megathrust_id,date,year,month,month_name
0,a4b01772-b735-4621-8a86-5c00c2367ab6,1c2639a3-f336-4c06-a4e4-a341c8be27ea,2024-01-01 13:46:45.922,-6.6246,107.7514,4.5,10.000,Jawa Barat,NaN,2024-01-01,2024,1,January
1,c7d24fdb-1f06-45a6-9fd7-03b12985c0a2,2b1b177b-b16d-439f-ad73-6020479b52e6,2024-01-01 07:52:43.251,-0.1092,123.6177,5.3,81.212,Sulawesi Utara,NaN,2024-01-01,2024,1,January
2,3b2a4091-8bbb-4c19-9e0a-0c462fc425a9,ad662a32-5c83-4457-89ae-1b17fa08d474,2024-01-01 05:22:53.884,-7.8936,117.8591,4.7,10.000,Sulawesi Selatan,NaN,2024-01-01,2024,1,January
3,23ab9c92-b0e5-4d25-a0f8-c2dbe73e4a08,1c2639a3-f336-4c06-a4e4-a341c8be27ea,2023-12-31 13:34:21.255,-6.7592,107.8299,4.8,12.158,Jawa Barat,NaN,2023-12-31,2023,12,December
4,aa49a60c-1d77-4f0d-b555-021bbf0d50a7,7bbb1a43-2607-492c-a4cf-42de2b54b72f,2023-12-30 17:16:23.833,-2.9934,139.3720,6.3,33.000,Papua,NaN,2023-12-30,2023,12,December

kategori Depth

In [14]:
def depth_category(depth):
    if pd.isna(depth):
        return None
    elif depth < 60:
        return "dangkal"
    elif depth <= 300:
        return "menengah"
    else:
        return "dalam"
    
df["depth_category"] = df["depth"].apply(depth_category)

In [15]:
df.head()

,id,province_id,time,latitude,longitude,magnitude,depth,place,fault_megathrust_id,date,year,month,month_name,depth_category
0,a4b01772-b735-4621-8a86-5c00c2367ab6,1c2639a3-f336-4c06-a4e4-a341c8be27ea,2024-01-01 13:46:45.922,-6.6246,107.7514,4.5,10.000,Jawa Barat,NaN,2024-01-01,2024,1,January,dangkal
1,c7d24fdb-1f06-45a6-9fd7-03b12985c0a2,2b1b177b-b16d-439f-ad73-6020479b52e6,2024-01-01 07:52:43.251,-0.1092,123.6177,5.3,81.212,Sulawesi Utara,NaN,2024-01-01,2024,1,January,menengah
2,3b2a4091-8bbb-4c19-9e0a-0c462fc425a9,ad662a32-5c83-4457-89ae-1b17fa08d474,2024-01-01 05:22:53.884,-7.8936,117.8591,4.7,10.000,Sulawesi Selatan,NaN,2024-01-01,2024,1,January,dangkal
3,23ab9c92-b0e5-4d25-a0f8-c2dbe73e4a08,1c2639a3-f336-4c06-a4e4-a341c8be27ea,2023-12-31 13:34:21.255,-6.7592,107.8299,4.8,12.158,Jawa Barat,NaN,2023-12-31,2023,12,December,dangkal
4,aa49a60c-1d77-4f0d-b555-021bbf0d50a7,7bbb1a43-2607-492c-a4cf-42de2b54b72f,2023-12-30 17:16:23.833,-2.9934,139.3720,6.3,33.000,Papua,NaN,2023-12-30,2023,12,December,dangkal

standasisasi nama provinsi

In [16]:
df["place"] = (
    df["place"]
    .str.strip()
    .str.title()
)
ordered_cols = [
    "id",
    "province_id",
    "place",
    "time",
    "date",
    "month",
    "month_name",
    "year",
    "latitude",
    "longitude",
    "magnitude",
    "depth",
    "depth_category",
    "fault_megathrust_id"
]

df = df[ordered_cols]
df.head()

,id,province_id,place,time,date,month,month_name,year,latitude,longitude,magnitude,depth,depth_category,fault_megathrust_id
0,a4b01772-b735-4621-8a86-5c00c2367ab6,1c2639a3-f336-4c06-a4e4-a341c8be27ea,Jawa Barat,2024-01-01 13:46:45.922,2024-01-01,1,January,2024,-6.6246,107.7514,4.5,10.000,dangkal,NaN
1,c7d24fdb-1f06-45a6-9fd7-03b12985c0a2,2b1b177b-b16d-439f-ad73-6020479b52e6,Sulawesi Utara,2024-01-01 07:52:43.251,2024-01-01,1,January,2024,-0.1092,123.6177,5.3,81.212,menengah,NaN
2,3b2a4091-8bbb-4c19-9e0a-0c462fc425a9,ad662a32-5c83-4457-89ae-1b17fa08d474,Sulawesi Selatan,2024-01-01 05:22:53.884,2024-01-01,1,January,2024,-7.8936,117.8591,4.7,10.000,dangkal,NaN
3,23ab9c92-b0e5-4d25-a0f8-c2dbe73e4a08,1c2639a3-f336-4c06-a4e4-a341c8be27ea,Jawa Barat,2023-12-31 13:34:21.255,2023-12-31,12,December,2023,-6.7592,107.8299,4.8,12.158,dangkal,NaN
4,aa49a60c-1d77-4f0d-b555-021bbf0d50a7,7bbb1a43-2607-492c-a4cf-42de2b54b72f,Papua,2023-12-30 17:16:23.833,2023-12-30,12,December,2023,-2.9934,139.3720,6.3,33.000,dangkal,NaN

In [20]:
df.to_csv("data/data_gempa_preprocessed.csv", index=False)